---
language: php
sudo: false
matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
  fast_finish: true
cache:
  directories:
    - $HOME/.composer/cache

before_install:
# Remove xdebug as per https://getcomposer.org/doc/articles/troubleshooting.md#xdebug-impact-on-composer
  - composer self-update
  - composer validate

install:
  - composer install --prefer-dist

script:
  - bin/phpcs --standard=phpcs.xml src
  - bin/phpspec run --no-code-generation --format=pretty
...
