# https://docs.github.com/en/actions

name: "Integrate"

on: # yamllint disable-line rule:truthy
  pull_request: null
  push:
    branches:
      - "main"

jobs:
  hello:
    name: "Hello"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Say hello"
        run: "echo 'Hello!'"
